name: Unit Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  laravel-tests:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        php: [8.0, 7.4]
        dependency-version: [prefer-lowest, prefer-stable]
        os: [ubuntu-latest, windows-latest]

    name: PHP ${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: pcov

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache/files
        key: dependencies-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

    - name: Install dependencies
      run: composer update --no-interaction --no-suggest --prefer-dist --${{ matrix.dependency-version }}

    - name: Sniff the code
      run: vendor/bin/phpcs --standard=./ruleset.xml --extensions=php ./

    - name: Execute tests using PHPUnit
      run: ./vendor/bin/phpunit ./tests --coverage-text
